### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by BBBruceYang** [IllusiveNetworks-Labs/HistoricProcessTree#1]

**Comment by BBBruceYang** [comment]
It comes an error.
Processing...
Traceback (most recent call last):
  File "HistoricProcessTree.py", line 22, in <module>
        exit(main(args))
  File "HistoricProcessTree.py", line 9, in main processes_obj.getCreatedProcesses()
  File "C:\Users\User\Desktop\HistoricProcessTree-master\process_create_event.py", line 81, in getCreatedProcesses
       relevant_events = self.sort_events()
  File "C:\Users\User\Desktop\HistoricProcessTree-master\process_create_event.py", line 59, in sort_events
        xmldata = item.get('MS').get('S')['#text']
TypeError: 'NoneType' object has no attribute '__getitem__'
